rvm: 2.4.1
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
env:
  global:
    - secure: "TcAcr7mcOh/OrZ956ZeUxsXNAoHlW1z7ADdzIqJtmYrVJ8Szq8ct5qc+sAuPi1xV82gT39rebT2dhvMG8O2J6b4MkZ/NTe1mIIq4koKxa+zS3vfuuabnrqXeTVN9qF8udpZ6PQsFJrHyGcsVCLplOXkLc9dDRyvMosHCHJuMAUtfernwjLYVStDreSpWEl6Q9WeHHs841GkbRSCOQI2A9h/UH8JWpLt41KCSs9GRhfPmF06ZMYQ/TSEEVtsD0MNlGkUdyxWzn9Q0c2ukebGs82YWoH7ZigpSoPQ5n94YPSsjadyQ8dd/eAMexwtGEFzYeOL8UTBYtKP/6BUV5Lo/XKb0U1vlFBDabzU8R8tiXVtJ3JTWed4pfZXYb3AnDfLXnqV7/Bymve8jtX8wVa3bUKZMtkqnLCMrpiXUXlmreT1tCrWMf/60xtGdyjvmMRZBib64ln9xqMkSSc+8UyGWj9kBHbT91ZNs/JJ+k1uVjRVBQ0rkWF/PBweWKF2rEfqutzt+W0v8p6voy7Gf/x30fxRZO1QpdbCCRYura4iDxP+d6AAO2hdNVU16x1a8kam4iLgBa+EL4AuRSOC2N402eI8622UOl9nhPU0o0gJm1KwHNfGnKAiMZVb9ZCAxHTPy2VWNrB0VUPXHnpzzMmciaEi3uxdMbCdlcnWIlPb+u1o="