rvm: 2.4.1
script:
- bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: _site
  fqdn: po.pdis.rocks
  on:
    branch: master