language: ruby
rvm: 2.7.2
script:
- bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: _site
  fqdn: po.pdis.tw
  on:
    branch: master
