author: PDIS
email: hello@pdis.tw
lang: zh-TW
baseurl: "" # the subpath of your site, e.g. /blog
logo: 
image: 
sass:
  style: compressed

exclude: ["README.md", "Gemfile", "Gemfile.lock"]

twitter_username: TaiwanPDIS
github_username: pdis
google_analytics: 

# --------- i18n settings ---------
languages: ["en", "zh-TW"]
exclude_from_localizations: ["assets", "CNAME", "favicon.ico"]
defaultLang: en
languageNames:
  zh-TW: 繁體中文
  en: English
